version: '3.8'
services:
  go-admin-api:
    container_name: gvaadmin
    image: gvaadmin:main-V1.0.1
    privileged: true
    restart: always
    ports:
      - 66:80
    volumes:
      - ./scripts/nginx/api_proxy.conf:/etc/nginx/conf.d/api_proxy.conf
    networks:
      - myweb
networks:
  myweb:
    driver: bridge
